<?php
/**
 * @file
 * home_page.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function home_page_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function home_page_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_image_default_styles().
 */
function home_page_image_default_styles() {
  $styles = array();

  // Exported image style: sponsor_banner.
  $styles['sponsor_banner'] = array(
    'name' => 'sponsor_banner',
    'label' => 'Sponsor Banner',
    'effects' => array(),
  );

  return $styles;
}
